export const LOAD_DB = 'LOAD_DB';
export const LOAD_DB_BEGIN = 'LOAD_DB_BEGIN';
export const LOAD_DB_SUCCESS = 'LOAD_DB_SUCCESS';
export const LOAD_DB_ERROR = 'LOAD_DB_ERROR';

export const ADD_STAFFING_SUCCESS = 'ADD_STAFFING_SUCCESS';

export const CLOSE_PROJECT_SUCCESS = 'CLOSE_PROJECT_SUCCESS';

export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const ADD_USER_CUSTOM_DAY_SUCCESS = 'ADD_USER_CUSTOM_DAY_SUCCESS';
export const UPDATE_USER_CUSTOM_DAY_SUCCESS = 'UPDATE_USER_CUSTOM_DAY_SUCCESS';
